### ISSUE TITLE
'Enter' key behaviour on Question modal is unexpected

### ISSUE THREAD

**Issue by magg01** [agiledev3/buyers-remorse-app#28]
When answering a consideration question on desktop, entering the answer and hitting the enter key on the keyboard loses the user input and refreshes the page. The question remains unanswered and is re-presented to the user on re-clicking of the question button.

This issue, I believe, makes our UI fall foul of Nielsen's usability heuristics, specifically _#7: Flexibility and efficiency of use_ (providing keyboard shortcuts) and _#9: Help users recognize, diagnose, and recover from errors_ as it doesn't inform users of the loss of their data.

**Comment by dmytrokulak** [comment]
This issue is an example of generally poor handling of keyboard and device controls navigation throughout our app. You must have bumped into the most prominent flaw but there must be others also.

**Comment by dmytrokulak** [comment]
lets continue in Trello, btw. Using github issues feels like a duplication, imho

**Comment by magg01** [comment]
Do you mean continue this discussion in Trello or continue reporting issues/bugs in Trello? I primarily recorded the issue because I hadn't used one in conjunction with a PR before so wanted to see how that worked, but Trello is fine for future things if you think that's best.
